In [16]:
!pip install -q -r requirements.txt

  error: subprocess-exited-with-error
  
  × Building wheel for ConfigSpace (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [41 lines of output]
      C:\Users\HP\AppData\Local\Temp\pip-build-env-tkb98ehd\overlay\Lib\site-packages\setuptools\dist.py:738: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
        warnings.warn(
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-3.9
      creating build\lib.win-amd64-3.9\ConfigSpace
      copying ConfigSpace\exceptions.py -> build\lib.win-amd64-3.9\ConfigSpace
      copying ConfigSpace\__init__.py -> build\lib.win-amd64-3.9\ConfigSpace
      copying ConfigSpace\__version__.py -> build\lib.win-amd64-3.9\ConfigSpace
      creating build\lib.win-amd64-3.9\ConfigSpace\nx
      copying ConfigSpace\nx\exception.py -> build\lib.win-amd64-3.9\ConfigSpa

new line

In [15]:
!pip install --help


Usage:   
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

Description:
  Install packages from:
  
  - PyPI (and other indexes) using requirement specifiers.
  - VCS project urls.
  - Local project directories.
  - Local or remote source archives.
  
  pip also supports installing from "requirements files", which provide
  an easy way to specify a whole environment to be installed.

Install Options:
  -r, --requirement <file>    Install from the given requirements file. This
                              option can be used multiple times.
  -c, --constraint <file>     Constrain versions using the given constraints
                              file. This option can be used multiple times.
  --no-deps                   Don't install p

In [17]:
import numpy as np

# This is John's data
data = np.array([[0, 1, 5, 1, 0],  # record of John's 1st food delivery
                [1, 0, 7, 0, 1],   # record of John's 2nd food delivery
                [0, 1, 2, 1, 0],   # record of John's 3rd food delivery
                [1, 1, 4.2, 1, 0], # record of John's 4th food delivery
                [0, 0, 7.8, 0, 1], # ...
                [1, 0, 3.9, 1, 0],
                [0, 1, 4, 1, 0],
                [1, 1, 2, 0, 0],
                [0, 0, 3.5, 0, 1],
                [1, 0, 2.6, 1, 0],
                [0, 0, 4.1, 0, 1],
                [0, 1, 1.5, 0, 1],
                [1, 1, 1.75, 1, 0],
                [1, 0, 1.3, 0, 0],
                [1, 1, 2.1, 0, 0],
                [1, 1, 0.2, 1, 0],
                [1, 1, 5.2, 0, 1],
                [0, 1, 2, 1, 0],
                [1, 0, 5.5, 0, 1],
                [0, 0, 2, 1, 0],
                [1, 1, 1.7, 0, 0],
                [0, 1, 3, 1, 1],
                [1, 1, 1.9, 1, 0],
                [0, 1, 3.1, 0, 1],
                [0, 1, 2.3, 0, 0],
                [0, 0, 1.1, 1, 0],
                [1, 1, 2.5, 1, 1],
                [1, 1, 5, 0, 1],
                [1, 0, 7.5, 1, 1],
                [0, 0, 0.5, 1, 0],
                [0, 0, 1.5, 1, 0],
                [1, 0, 3.2, 1, 0],
                [0, 0, 2.15, 1, 0],
                [1, 1, 4.2, 0, 1],
                [1, 0, 6.5, 0, 1],
                [1, 0, 0.5, 0, 0],
                [0, 0, 3.5, 0, 1],
                [0, 0, 1.75, 0, 0],
                [1, 1, 5, 0, 1],
                [0, 0, 2, 1, 0],
                [0, 1, 1.3, 1, 1],
                [0, 1, 0.2, 0, 0],
                [1, 1, 2.2, 0, 0],
                [0, 1, 1.2, 1, 0],
                [1, 1, 4.2, 0, 1]])

print(data)

[[0.   1.   5.   1.   0.  ]
 [1.   0.   7.   0.   1.  ]
 [0.   1.   2.   1.   0.  ]
 [1.   1.   4.2  1.   0.  ]
 [0.   0.   7.8  0.   1.  ]
 [1.   0.   3.9  1.   0.  ]
 [0.   1.   4.   1.   0.  ]
 [1.   1.   2.   0.   0.  ]
 [0.   0.   3.5  0.   1.  ]
 [1.   0.   2.6  1.   0.  ]
 [0.   0.   4.1  0.   1.  ]
 [0.   1.   1.5  0.   1.  ]
 [1.   1.   1.75 1.   0.  ]
 [1.   0.   1.3  0.   0.  ]
 [1.   1.   2.1  0.   0.  ]
 [1.   1.   0.2  1.   0.  ]
 [1.   1.   5.2  0.   1.  ]
 [0.   1.   2.   1.   0.  ]
 [1.   0.   5.5  0.   1.  ]
 [0.   0.   2.   1.   0.  ]
 [1.   1.   1.7  0.   0.  ]
 [0.   1.   3.   1.   1.  ]
 [1.   1.   1.9  1.   0.  ]
 [0.   1.   3.1  0.   1.  ]
 [0.   1.   2.3  0.   0.  ]
 [0.   0.   1.1  1.   0.  ]
 [1.   1.   2.5  1.   1.  ]
 [1.   1.   5.   0.   1.  ]
 [1.   0.   7.5  1.   1.  ]
 [0.   0.   0.5  1.   0.  ]
 [0.   0.   1.5  1.   0.  ]
 [1.   0.   3.2  1.   0.  ]
 [0.   0.   2.15 1.   0.  ]
 [1.   1.   4.2  0.   1.  ]
 [1.   0.   6.5  0.   1.  ]
 [1.   0.   0.5  0. 

In [18]:
import pandas as pd

# Create the dataframe with this data, labeling the columns
delivery_data = pd.DataFrame(data, columns=["bad_weather", "is_rush_hour", "mile_distance", "urban_address", "late"])

In [19]:
# Print the first 5 rows
delivery_data.head(15)

bad_weather  is_rush_hour  mile_distance  urban_address  late
0           0.0           1.0           5.00            1.0   0.0
1           1.0           0.0           7.00            0.0   1.0
2           0.0           1.0           2.00            1.0   0.0
3           1.0           1.0           4.20            1.0   0.0
4           0.0           0.0           7.80            0.0   1.0
5           1.0           0.0           3.90            1.0   0.0
6           0.0           1.0           4.00            1.0   0.0
7           1.0           1.0           2.00            0.0   0.0
8           0.0           0.0           3.50            0.0   1.0
9           1.0           0.0           2.60            1.0   0.0
10          0.0           0.0           4.10            0.0   1.0
11          0.0           1.0           1.50            0.0   1.0
12          1.0           1.0           1.75            1.0   0.0
13          1.0           0.0           1.30            0.0   0.0
14          1.0           1.0           2.10            0.0   0.0

In [20]:
input_data = delivery_data[["bad_weather", "is_rush_hour", "mile_distance", "urban_address"]]
target = delivery_data["late"]

In [21]:
from sklearn.neighbors import KNeighborsClassifier

# Use n_neighbors = 1
# This means the KNN will consider the "closest" record to make a decision.
classifier = KNeighborsClassifier(n_neighbors = 1)

# Fit the model to our data
classifier.fit(input_data, target)

KNeighborsClassifier(n_neighbors=1)

In [22]:
import numpy as np

some_data = np.array([[0, 0, 2.1, 1]]) # bad_weather->0, is_rush_hour->0, mile_distance->2.1 and urban_address->1

# Use the fitted model to make predictions on new data
print(classifier.predict(some_data))

[0.]


On time

In [23]:
import numpy as np

some_data = np.array([[0, 0, 2.1, 1], # bad_weather->0, is_rush_hour->0, mile_distance->2.1 and urban_address->1
                 [0, 1, 5, 0],   # bad_weather->0, is_rush_hour->1, mile_distance->5.0 and urban_address->0
                 [1, 1, 3.1, 1]  # bad_weather->1, is_rush_hour->1, mile_distance->3.1 and urban_address->1
                ])

# Use the fitted model to make predictions on more new data
print(classifier.predict(some_data))

[0. 0. 1.]


In [24]:
# Use the fitted model to make predictions on our training dataset
predictions = classifier.predict(input_data)

In [25]:
from sklearn.metrics import confusion_matrix

print(confusion_matrix(target, predictions))

[[27  0]
 [ 0 18]]


In [26]:
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score

print(classification_report(target, predictions))

print("Accuracy:", accuracy_score(target, predictions))

              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00        27
         1.0       1.00      1.00      1.00        18

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

Accuracy: 1.0


In [27]:
delivery_data.shape

(45, 5)

In [28]:
# Let's split our data into two sets: Training (85%) and Test (15%)
# This gives us 38 training records and 7 test records (total 45 records)

training_data = delivery_data.iloc[:38, :] # First 38
test_data = delivery_data.iloc[38:, :] # Remaining

# Print the first 5 rows
training_data.head()

bad_weather  is_rush_hour  mile_distance  urban_address  late
0          0.0           1.0            5.0            1.0   0.0
1          1.0           0.0            7.0            0.0   1.0
2          0.0           1.0            2.0            1.0   0.0
3          1.0           1.0            4.2            1.0   0.0
4          0.0           0.0            7.8            0.0   1.0

In [29]:
from sklearn.neighbors import KNeighborsClassifier

X_train = training_data[["bad_weather", "is_rush_hour", "mile_distance", "urban_address"]].values
y_train = training_data["late"].tolist()

# Use n_neighbors = 1
# This means the KNN will consider two other "closest" records to make a decision.
classifier = KNeighborsClassifier(n_neighbors = 1)

# Fit the model to our training data
classifier.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=1)

In [30]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

# Use the fitted model to make predictions on the same dataset we trained the model on
train_predictions = classifier.predict(X_train)

print('Model evaluation on the training set: \n')
print(confusion_matrix(y_train, train_predictions))
print(classification_report(y_train, train_predictions))
print("Training accuracy:", accuracy_score(y_train, train_predictions))

Model evaluation on the training set: 

[[23  0]
 [ 0 15]]
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00        23
         1.0       1.00      1.00      1.00        15

    accuracy                           1.00        38
   macro avg       1.00      1.00      1.00        38
weighted avg       1.00      1.00      1.00        38

Training accuracy: 1.0


In [31]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

X_test = test_data[["bad_weather", "is_rush_hour", "mile_distance", "urban_address"]].values
y_test = test_data["late"].tolist()

# Use the fitted model to make predictions on the test dataset
test_predictions = classifier.predict(X_test)

print('Model evaluation on the training set: \n')
print(confusion_matrix(y_test, test_predictions))
print(classification_report(y_test, test_predictions))
print("Training accuracy:", accuracy_score(y_test, test_predictions))

Model evaluation on the training set: 

[[3 1]
 [1 2]]
              precision    recall  f1-score   support

         0.0       0.75      0.75      0.75         4
         1.0       0.67      0.67      0.67         3

    accuracy                           0.71         7
   macro avg       0.71      0.71      0.71         7
weighted avg       0.71      0.71      0.71         7

Training accuracy: 0.7142857142857143


In [32]:
# Let's further split our training data into two sets: Training (80%) and Validation (20%)
# This gives us 30 training records and 8 test records 

train_data = training_data.iloc[:30, :] # First 30
val_data = training_data.iloc[30:, :] # Remaining

X_train = train_data[["bad_weather", "is_rush_hour", "mile_distance", "urban_address"]].values
y_train = train_data["late"].tolist()

X_val = val_data[["bad_weather", "is_rush_hour", "mile_distance", "urban_address"]].values
y_val =val_data["late"].tolist()

In [33]:
K_values = [1, 2, 3, 4, 5, 6]

for K in K_values:
    classifier = KNeighborsClassifier(n_neighbors = K)
    classifier.fit(X_train, y_train)
    val_predictions = classifier.predict(X_val)
    print("K=%d, Validation accuracy score: %f" % (K, accuracy_score(y_val, val_predictions)))

K=1, Validation accuracy score: 0.875000
K=2, Validation accuracy score: 0.875000
K=3, Validation accuracy score: 1.000000
K=4, Validation accuracy score: 1.000000
K=5, Validation accuracy score: 1.000000
K=6, Validation accuracy score: 0.875000


In [34]:
classifier = KNeighborsClassifier(n_neighbors = 4)
classifier.fit(X_train, y_train)
test_predictions = classifier.predict(X_test)
print("Test accuracy score: %f" % (accuracy_score(y_test, test_predictions)))

Test accuracy score: 0.857143
